FA.ScoreManagement.MVC/Areas/Admin/Controllers/SubjectController.cs
using AutoMapper;
using FA.ScoreManagement.Common;
using FA.ScoreManagement.Data.Entities;
using FA.ScoreManagement.Models.Subject;
using FA.ScoreManagement.Repository.UnitOfWork;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FA.ScoreManagement.MVC.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "SuperAdmin")]
    public class SubjectController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IMapper _mapper;
        private readonly UserManager<AppUser> _userManager;
        private readonly SignInManager<AppUser> _signInManager;

        public SubjectController(IUnitOfWork unitOfWork, IMapper mapper, UserManager<AppUser> userManager, SignInManager<AppUser> signInManager)
        {
            _unitOfWork = unitOfWork;
            _mapper = mapper;
            _userManager = userManager;
            _signInManager = signInManager;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult GetAll(string status)
        {
            var subjects = _unitOfWork.SubjectRepository.GetAll();
            var subjectVMs = _mapper.Map<IList<Subject>, IList<GetSubjectVM>>(subjects);
            foreach (var item in subjectVMs)
            {
                var classAssign = _unitOfWork.ClassAssignRepository.GetAll(includeProperties: "Teacher,Subject,Class,Semester,SchoolYear").FirstOrDefault(x => x.SubjectId == item.Id);
                item.TeacherAssigned = classAssign.Teacher.FullName;
                item.ClassAssigned = classAssign.Class.Name;
                item.SemesterAssigned = classAssign.Semester.Name;
                item.SchoolYearAssigned = classAssign.SchoolYear.Name;
            }

            return Json(new { data = subjectVMs });
        }

        [HttpGet]
        public IActionResult Create()
        {
            var teachers = _userManager.GetUsersInRoleAsync("Teacher").Result;
            ViewBag.TeacherAssign = new SelectList(teachers, "Id", "FullName", teachers[0].FullName);
            var classes = _unitOfWork.ClassRepository.GetAll();
            ViewBag.ClassAssign = new SelectList(classes, "Id", "Name", classes[0].Name);
            var semesters = _unitOfWork.SemesterRepository.GetAll();
            ViewBag.SemesterAssign = new SelectList(semesters, "Id", "Name", semesters[0].Name);
            var schoolYears = _unitOfWork.SchoolYearRepository.GetAll();
            ViewBag.SchoolYearAssign = new SelectList(schoolYears, "Id", "Name", schoolYears[0].Name);
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(SubjectVM subjectVM)
        {
            if (!ModelState.IsValid)
            {
                var teachers = _userManager.GetUsersInRoleAsync("Teacher").Result;
                ViewBag.TeacherAssign = new SelectList(teachers, "Id", "FullName", teachers[0].FullName);
                var classes = _unitOfWork.ClassRepository.GetAll();
                ViewBag.ClassAssign = new SelectList(classes, "Id", "Name", classes[0].Name);
                var semesters = _unitOfWork.SemesterRepository.GetAll();
                ViewBag.SemesterAssign = new SelectList(semesters, "Id", "Name", semesters[0].Name);
                var schoolYears = _unitOfWork.SchoolYearRepository.GetAll();
                ViewBag.SchoolYearAssign = new SelectList(schoolYears, "Id", "Name", schoolYears[0].Name);
                return View();
            }
            var subject = _mapper.Map<Subject>(subjectVM);
            subject.Status = Status.Active;
            _unitOfWork.SubjectRepository.Add(subject);
            _unitOfWork.SaveChange();
            var classAssign = new ClassAssign();
            classAssign.SubjectId = subject.Id;
            classAssign.TeacherId = subjectVM.TeacherAssignId;
            classAssign.ClassId = subjectVM.ClassAssignedId;
            classAssign.SemesterId = subjectVM.SemesterAssignedId;
            classAssign.SchoolYearId = subjectVM.SchoolYearAssignedId;

            _unitOfWork.ClassAssignRepository.Add(classAssign);
            await _unitOfWork.SaveChangeAsync();

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var subject = _unitOfWork.SubjectRepository.Find(id);
            var result = _mapper.Map<Subject, SubjectVM>(subject);
            var classAssign = _unitOfWork.ClassAssignRepository.GetAll().FirstOrDefault(x => x.SubjectId == id);
            result.TeacherAssignId = classAssign.TeacherId;
            result.ClassAssignedId = classAssign.ClassId;
            result.SemesterAssignedId = classAssign.SemesterId;
            result.SchoolYearAssignedId = classAssign.SchoolYearId;

            var teachers = _userManager.GetUsersInRoleAsync("Teacher").Result;
            ViewBag.TeacherAssign = new SelectList(teachers, "Id", "FullName");
            var classes = _unitOfWork.ClassRepository.GetAll();
            ViewBag.ClassAssign = new SelectList(classes, "Id", "Name");
            var semesters = _unitOfWork.SemesterRepository.GetAll();
            ViewBag.SemesterAssign = new SelectList(semesters, "Id", "Name");
            var schoolYears = _unitOfWork.SchoolYearRepository.GetAll();
            ViewBag.SchoolYearAssign = new SelectList(schoolYears, "Id", "Name");
            return View(result);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(SubjectVM subjectVM)
        {
            var subject = _mapper.Map<Subject>(subjectVM);
            _unitOfWork.SubjectRepository.Update(subject);
            var classAssign = _unitOfWork.ClassAssignRepository.GetAll().FirstOrDefault(x => x.SubjectId == subject.Id);
            if (classAssign.TeacherId != subjectVM.TeacherAssignId || classAssign.ClassId != subjectVM.ClassAssignedId || classAssign.SemesterId != subjectVM.SemesterAssignedId || classAssign.SchoolYearId != subjectVM.SchoolYearAssignedId)
            {
                var newClassAssign = new ClassAssign()
                {
                    SubjectId = subjectVM.Id,
                    TeacherId = subjectVM.TeacherAssignId,
                    ClassId = subjectVM.ClassAssignedId,
                    SemesterId = subjectVM.SemesterAssignedId,
                    SchoolYearId = subjectVM.SchoolYearAssignedId
                };
                _unitOfWork.ClassAssignRepository.Add(newClassAssign);
                _unitOfWork.ClassAssignRepository.Delete(classAssign);
                _unitOfWork.SaveChange();
            }
            await _unitOfWork.SaveChangeAsync();

            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> ChangeState(int id)
        {
            var subject = _unitOfWork.SubjectRepository.Find(id);
            if (subject.Status == Status.InActive)
            {
                subject.Status = Status.Active;
            }
            else
            {
                subject.Status = Status.InActive;
            }
            _unitOfWork.SubjectRepository.Update(subject);
            await _unitOfWork.SaveChangeAsync();
            return RedirectToAction("Index");
        }
    }
}

FA.ScoreManagement.MVC/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Hosting
@using Microsoft.AspNetCore.Mvc.ViewEngines
@inject IWebHostEnvironment Environment
@inject ICompositeViewEngine Engine
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FA.ScoreManagement.MVC</title>
    <link rel="stylesheet" href="~/Identity/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/Identity/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-light navbar-toggleable-sm bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" href="~/">FA.ScoreManagement.MVC</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    @{
                        var result = Engine.FindView(ViewContext, "_LoginPartial", isMainPage: false);
                    }
                    @if (result.Success)
                    {
                        await Html.RenderPartialAsync("_LoginPartial");
                    }
                    else
                    {
                        throw new InvalidOperationException("The default Identity UI layout requires a partial view '_LoginPartial' " +
                            "usually located at '/Pages/_LoginPartial' or at '/Views/Shared/_LoginPartial' to work. Based on your configuration " +
                            $"we have looked at it in the following locations: {System.Environment.NewLine}{string.Join(System.Environment.NewLine, result.SearchedLocations)}.");
                    }
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="footer border-top text-muted">
        <div class="container">
            &copy; 2022 - FA.ScoreManagement.MVC - <a asp-area="" asp-page="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/Identity/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/Identity/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/Identity/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

FA.ScoreManagement.MVC/Views/Shared/_LayoutAdmin.cshtml
@using FA.ScoreManagement.Data.Entities
@using Microsoft.AspNetCore.Identity
@inject UserManager<AppUser> userManager
@{
    var user = userManager.GetUserAsync(User).Result;
}

<!DOCTYPE html>
<html dir="ltr" lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="noindex,nofollow">
    <title>School Management</title>
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="~/admin/assets/images/logo-icon.png">
    <!-- Custom CSS -->
    <link href="~/admin/assets/plugins/chartist/dist/chartist.min.css" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="~/admin/css/style.min.css" rel="stylesheet">
    <link rel="stylesheet" href="//cdn.datatables.net/1.11.2/css/jquery.dataTables.min.css" />
</head>

<body>
    <!-- ============================================================== -->
    <!-- Preloader - style you can find in spinners.css -->
    <!-- ============================================================== -->
    <div class="preloader">
        <div class="lds-ripple">
            <div class="lds-pos"></div>
            <div class="lds-pos"></div>
        </div>
    </div>
    <!-- ============================================================== -->
    <!-- Main wrapper - style you can find in pages.scss -->
    <!-- ============================================================== -->
    <div id="main-wrapper" data-layout="vertical" data-navbarbg="skin6" data-sidebartype="full"
         data-sidebar-position="absolute" data-header-position="absolute" data-boxed-layout="full">
        <!-- ============================================================== -->
        <!-- Topbar header - style you can find in pages.scss -->
        <!-- ============================================================== -->
        <header class="topbar" data-navbarbg="skin6">
            <nav class="navbar top-navbar navbar-expand-md navbar-dark">
                <div class="navbar-header" data-logobg="skin6">
                    <!-- ============================================================== -->
                    <!-- Logo -->
                    <!-- ============================================================== -->
                    <a class="navbar-brand" asp-action="Index" asp-controller="Home" asp-area="Admin">
                        <!-- Logo icon -->
                        <b class="logo-icon">
                            <!--You can put here icon as well // <i class="wi wi-sunset"></i> //-->
                            <!-- Dark Logo icon -->
                            <img src="~/admin/assets/images/logo-icon.png" alt="homepage" style="margin-left:60px" class="dark-logo" />
                        </b>
                        <!--End Logo icon -->
                        <!-- Logo text -->
                    </a>
                    <!-- ============================================================== -->
                    <!-- End Logo -->
                    <!-- ============================================================== -->
                    <!-- ============================================================== -->
                    <!-- toggle and nav items -->
                    <!-- ============================================================== -->
                </div>
                <!-- ============================================================== -->
                <!-- End Logo -->
                <!-- ============================================================== -->
                <div class="navbar-collapse collapse" id="navbarSupportedContent" data-navbarbg="skin5">

                    <!-- ============================================================== -->
                    <!-- toggle and nav items -->
                    <!-- ============================================================== -->
                    <ul class="navbar-nav me-auto mt-md-0 ">
                    </ul>

                    <!-- ============================================================== -->
                    <!-- Right side toggle and nav items -->
                    <!-- ============================================================== -->
                    <ul class="navbar-nav">
                        <!-- ============================================================== -->
                        <!-- User profile and search -->
                        <!-- ============================================================== -->
                        <li class="nav-item dropdown">
                            <form id="logoutForm" class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Student", new { area = "Student" })">
										<button id="logout" type="submit" style="background-color:#00B4D6;color:white;border:none;">@user.FullName</button>
							</form>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>
        <!-- ============================================================== -->
        <!-- End Topbar header -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Left Sidebar - style you can find in sidebar.scss  -->
        <!-- ============================================================== -->
        <aside class="left-sidebar" data-sidebarbg="skin6">
            <!-- Sidebar scroll-->
            <div class="scroll-sidebar">
                <!-- Sidebar navigation-->
                <nav class="sidebar-nav">
                    <ul id="sidebarnav">
                        <!-- User Profile-->
                        <li class="sidebar-item">
                            <a class="sidebar-link waves-effect waves-dark sidebar-link"
                               asp-action="Index" asp-controller="Class" asp-area="Admin" aria-expanded="false">
                                <i class="me-3 far fa-clock fa-fw"
                                   aria-hidden="true"></i><span class="hide-menu">Class</span>
                            </a>
                        </li>
                        <li class="sidebar-item">
                            <a  asp-controller="Subject" asp-area="Admin" asp-action="Index"  class="sidebar-link waves-effect waves-dark sidebar-link"
                               aria-expanded="false">
                                <i class="me-3 fa fa-table"
                                   aria-hidden="true"></i><span class="hide-menu">Subject</span>
                                </a>
                            </li>
                        <li class="sidebar-item">
                            <a class="sidebar-link waves-effect waves-dark sidebar-link"
                               asp-action="Index" asp-controller="Student" asp-area="Admin" aria-expanded="false">
                                <i class="me-3 fa fa-user" aria-hidden="true"></i><span class="hide-menu">Student</span>
                            </a>
                        </li>
                        <li class="sidebar-item">
                            <a class="sidebar-link waves-effect waves-dark sidebar-link"
                               asp-area="Admin" asp-controller="Teacher" asp-action="Index" aria-expanded="false">
                                <i class="me-3 fa fa-user" aria-hidden="true"></i><span class="hide-menu">Teacher</span>
                            </a>
                        </li>
@*                        <li class="sidebar-item">
                            <a class="sidebar-link waves-effect waves-dark sidebar-link"
                               asp-action="Index" asp-controller="ClassAssign" asp-area="Admin" aria-expanded="false">
                                <i class="me-3 fa fa-columns"
                                   aria-hidden="true"></i><span class="hide-menu">Class Assign</span>
                            </a>
                        </li>*@
                    </ul>

                </nav>
                <!-- End Sidebar navigation -->
            </div>
            <!-- End Sidebar scroll-->
        </aside>
        <!-- ============================================================== -->
        <!-- End Left Sidebar - style you can find in sidebar.scss  -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Page wrapper  -->
        <!-- ============================================================== -->
        <div class="page-wrapper">
            @RenderBody()
        </div>
        <!-- ============================================================== -->
        <!-- End Page wrapper  -->
        <!-- ============================================================== -->
    </div>
    <!-- ============================================================== -->
    <!-- End Wrapper -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- All Jquery -->
    <!-- ============================================================== -->
    <script src="~/admin/assets/plugins/jquery/dist/jquery.min.js"></script>
    <!-- Bootstrap tether Core JavaScript -->
    <script src="~/admin/assets/plugins/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/admin/js/app-style-switcher.js"></script>
    <!--Wave Effects -->
    <script src="~/admin/js/waves.js"></script>
    <!--Menu sidebar -->
    <script src="~/admin/js/sidebarmenu.js"></script>
    <!--Custom JavaScript -->
    <script src="~/admin/js/custom.js"></script>
    <!--This page JavaScript -->
    <!--flot chart-->
    <script src="~/admin/assets/plugins/flot/jquery.flot.js"></script>
    <script src="~/admin/assets/plugins/flot.tooltip/js/jquery.flot.tooltip.min.js"></script>
    <script src="~/admin/js/pages/dashboards/dashboard1.js"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="//cdn.datatables.net/1.11.2/js/jquery.dataTables.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>

FA.ScoreManagement.MVC/Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>
<html lang="vi">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="apple-itunes-app" content="app-id=1469388309">
    <meta name="google-play-app" content="app-id=com.dhcn.MyHAUI">
    <link rel="shortcut icon" href="~/assets/img/logosms.png">
    <title>Score Management System</title>
    <link rel="stylesheet" type="text/css" href="~/assets/lib/perfect-scrollbar/css/perfect-scrollbar.min.css" />
    <link rel="stylesheet" type="text/css" href="~/assets/lib/material-design-icons/css/material-design-iconic-font.min.css" />
    <link href="~/assets/lib/font-awesome-4.7.0/css/font-awesome.min.css" rel="stylesheet" />
    <link href="~/assets/vnkresource/css/flaticon.css" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="~/assets/lib/datetimepicker/css/bootstrap-datetimepicker.min.css" />
    <link rel="stylesheet" type="text/css" href="~/assets/lib/select2/css/select2.min.css" />
    <link rel="stylesheet" href="~/assets/css/style.css" type="text/css" />
    <link href="~/assets/css/kstyle.css" rel="stylesheet" />
    <script src="~/assets/lib/jquery/jquery.min.js" type="text/javascript"></script>
    <script src="~/assets/lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js" type="text/javascript"></script>
    <script src="~/assets/lib/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>
    <script src="~/assets/js/snowfall.jquery.min.js" type="text/javascript"></script>
</head>
<body>
    <div class="be-wrapper be-fixed-sidebar">
        <div class="be-content">
            <div class="main-content container-fluid">
                @RenderBody()
            </div>
        </div>

    </div>
    <div class="modal fade bs-example-modal-lg" id="kZoom">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content" id="kbox"></div>
        </div>
    </div>
    <script src="~/assets/js/kadmin.2.0.js"></script>
    <script src="~/assets/lib/moment.js/min/moment.min.js" type="text/javascript"></script>
    <script src="~/assets/lib/datetimepicker/js/bootstrap-datetimepicker.min.js" type="text/javascript"></script>
    <script src="~/assets/lib/select2/js/select2.min.js" type="text/javascript"></script>
    <script src="~/assets/js/main.js" type="text/javascript"></script>
    <script type="text/javascript">
    </script>
    <script type="text/javascript">
        $(document).ready(function() {
            App.init();

            var files = $('.sidebar-elements li a');
            for (var i = 0; i < files.length; i++) {
                if ($(files[i]).attr('href').toLowerCase() == location.pathname.toLowerCase() + location.search.toLowerCase()) {
                    $(files[i]).parent().attr('class', 'active');
                    var obj = $(files[i]).parent();
                    var iparent = 0;
                    while (iparent < 10) {
                        if (obj.attr('class') == 'parent')
                            obj.addClass('open');
                        obj = obj.parent();
                        iparent++;
                    }
                }
            }
        });
    </script>

    <script>(function(i, s, o, g, r, a, m) { i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function() { (i[r].q = i[r].q || []).push(arguments) }, i[r].l = 1 * new Date(); a = s.createElement(o), m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m) })(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga'); ga('create', 'UA-106198347-2', 'auto'); ga('send', 'pageview');</script>

    <div id="pdg"></div>
    <div id="notification"></div>
</body>
</html>